### ISSUE TITLE
Trailing ', ' in biases value for c family export

### ISSUE THREAD

**Issue by Etienne-DUPUIS** [CEA-LIST/N2D2#50]
in include/conv1.h:
```static const BDATA_T conv1_biases[CONV1_NB_OUTPUTS] = {0, 0, 0, 0, 0, 0**, **};```

Step to reproduce:
n2d2 /opt/N2D2/models/LeNet.ini -export C -nbbits 16 -calib -1

**Comment by davidbriand-cea** [comment]
Hi,
I think it should be resolved with the latest commit 724a91f

Keep me informed, thanks

**Comment by Etienne-DUPUIS** [comment]
Ok, it is fixed, thanks you :)

**Comment by Etienne-DUPUIS** [comment]
The error still persist for FC layers, it has only been fixed for CONV

**Comment by olivierbichler-cea** [comment]
This was fixed in commit 499ccef640c88643a95483ea45f7cdd65358b325. Closing.
